<?php
$this->title = "Список станций";
$this->headTitle($this->title);
?>
<div class="ajax_search">
    <input type="text" id="station_search" value="<?php echo $this->query; ?>"/>
</div>
<div class="table">
    <table class="stations">
        <?php
            echo $this->partialLoop('partials/station.phtml', $this->stations);
        ?>
    </table>
</div>
<?php if ($this->pages > 1) echo $this->partial('partials/pagination.phtml', array('controller'=>'station')); ?>