<?php
// Создаём meta тег Content-Type
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');  
// Указываем символ разделитель в теге title
$this->headTitle()->setSeparator(' - ');
// Определяем содержимое тега title
$this->headTitle()->prepend('ЖД::Админ');
// Выводим doctype, который считывается из application.ini
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    echo $this->headMeta();
    echo $this->headTitle();
    $this->headLink()->appendStylesheet('/css/style.css');
    echo $this->headLink()->appendStylesheet('/css/admin.css');
    $this->headScript()->prependFile('/js/jquery.js');
    $this->headScript()->appendFile('/js/main.js');
    echo $this->headScript();
    ?>
</head>
<body>
<div class="page">
    <div class="header">
        <div id="admin-header">
            Админ Панель<a class="guest_link" href="/">Гостевая панель</a>
            <div class="auth_block">
                <?php
                if (Zend_Auth::getInstance()->hasIdentity()) {
                    
                    $url = $this->url(array('module'=>'default','controller'=>'auth', 'action'=>'logout'),'default',true);
                    echo "<a href=\"{$url}\">Выход</a>";
                }
                else {
                    echo Zend_Registry::get('login_form');
                    echo "<div class='clear'></div>";
                }
                ?>
            </div>
            <div class="clear"></div>
        </div>
        
        <div id="header-menu">
            <ul>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller' => 'train','action' => 'index'),'default',true) ?>">Поезда</a></li>
                <li><a href="<?php echo $this->url(array('module'=>'admin','controller' => 'station','action' => 'index'),'default',true) ?>">Станции</a></li>
                <li><a href="<?php echo $this->url(array('controller' => 'train','action' => 'route'),'default',true) ?>">Поиск по маршруту</a></li>
                <li class="last"><a href="<?php echo $this->url(array('module'=>'admin','controller' => 'youtube','action' => 'index'),'default',true) ?>">Запросы Youtube</a></li>
                <!--<li class="last">
                    <div style="position:relative;width:200px;">
                        <iframe src="http://ru.thetimenow.com/clock/ukraine?t=n&amp;embed=1&amp;text=0.1&amp;textdate=15&amp;format=24&amp;digitalclock=20&amp;analogclock=30&amp;letter_spacing=1&amp;bordersize=1&amp;bordercolor=BCE2F7&amp;bgcolor=5C4B63&amp;colorloc=5C4B63&amp;colordigital=73D5FF&amp;colordate=73D5FF&amp;styleloc=normal&amp;styledigital=normal&amp;styledate=normal&amp;right=0" style="border:none;overflow:hidden;" height="50" scrolling="no" width="200"></iframe>
                    </div>
                </li>-->
            </ul>
        </div>
    </div>
    <div class="mainbar">
        <div class="patch_minheight"></div>
        <h1><?php echo $this->escape($this->title); ?></h1>
        <?php echo $this->layout()->content ?>
    </div>
    <div class="footer_guarantor"></div>
</div>
<div class="footer">
    <h1>(c) John McLane</h1>
</div>
</body>
</html>