<div class="pagination">
    <?php
    $current = $this->partial()->view->page;
    $total = $this->partial()->view->pages;
    $max = $this->partial()->view->pages_max_count;
    if ($total > $max && $current > ceil($max/2)) {
        $start = $current - floor($max/2);
        if ($start > ($total - ($max - 1))) $start = $total - ($max - 1);
        $end =  $start + ($max - 1);
        if ($end > $total) $end = $total;
    } elseif ($total < $max) {
        $start = 1;
        $end = $total;
    } else {
        $start = 1;
        $end = $max;
    }
    if ($this->partial()->view->query) $q = '&q='.urlencode($this->partial()->view->query);
    else $q = '';
    if ($current > 1) {
        if ($start > 1) echo '<a href="/'.$this->controller.'/?page=1'.$q.'"><<</a>';
        echo '<a href="/'.$this->controller.'/?page='.($current-1).$q.'"><</a>';
    }
    for ($p = $start; $p <= $end; $p++) {
        if ($p == $current) echo '<span>'.$p.'</span>';
        else echo '<a href="/'.$this->controller.'/?page='.$p.$q.'">'.$p.'</a>';
    }
    if ($current < $total) {
        echo '<a href="/'.$this->controller.'/?page='.($current+1).$q.'">></a>';
        if ($start < ($total - ($max - 1))) echo '<a href="/'.$this->controller.'/?page='.$total.$q.'">>></a>';
    }
    ?>
    <div class="clear"></div>
</div>